version: '3.3'

services:
  web:
    image: zamotaeff/skypro:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - "80:5000"
    environment:
      - DB_PASSWORD=$DB_PASSWORD
      - DB_USER=$DB_USER
      - DB_NAME=$DB_NAME
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
      - POSTGRES_NAME=$DB_NAME
